### ISSUE TITLE
Enhance `up ctp` to work with control planes made by spaces

### ISSUE THREAD

**Issue by AlainRoy** [upbound/up#355]
We should extend `up` to be able to interact with control planes made in a space (via `up space init`). This issue isn't (yet) prescriptive, but:

* There should be a command to easily get a kubeconfig for a control plane made in a space.
* There should be commands to create/list/get/delete control planes. 

There are a couple of options here:
* Extend the `up ctp` commands to work with Spaces control planes. Maybe add a new kind of profile that points at a space.
* Modify the commands so we have `up space ctp` and `up cloud ctp`.
* Other smart ideas we have. 

```[tasklist]
### Tasks
- [ ] https://github.com/upbound/up/issues/373
- [ ] https://github.com/upbound/up/issues/374
- [ ] https://github.com/upbound/up/issues/375
```

**Comment by RedbackThomson** [comment]
Closed as the introduction of spaces into cloud has fundamentally changed `up` and this is no longer applicable.
